name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'

runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo "Hello ${{ inputs.who-to-greet }}."
      shell: bash

    - name: Say Goodbye
      run: echo "Goodbye ${{ inputs.who-to-greet }}!"
      shell: bash
