on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: RehabAbotalep/learning-github-actions@V1
        with:
          who-to-greet: 'Rehab Ragab'
