name: "Greeting Workflow"

on:
  push:
    branches:
      - main

jobs:
  greet-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Hello World Action
        uses: ./.github/actions/hello-world-composite-action  # Reuse the composite action from the same repo
        with:
          who-to-greet: 'Rehab Ragab'        # Provide an input for the greeting