# This is a basic workflow to help you get started with Actions

name: Using environments to manually trigger workflow jobs

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run:
          echo 'building'

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: publish
        run:
          echo 'publishing'
