name: "Greeting Docker Workflow"

on: workflow_dispatch

jobs:
  greet-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Docker-based Hello World Action
        uses: ./.github/actions/hello-world-docker-action  # Path to your Docker action
        with:
          who-to-greet: 'Rehab Ragab'
