# This is a basic workflow to help you get started with Actions

name: Viewing all properties of an event

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT

  
