name: "Greeting JavaScript Action"

on: [push]

jobs:
  greet-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Hello World Action
        uses: ./.github/actions/hello-world-javascript-action  # Path to your JS action
        with:
          who-to-greet: 'Rehab Ragab'
