# This is a basic workflow to help you get started with Actions

name: Job Dependency

on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hell from Setup job"
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hell from Build job"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hell from Test job"
