name: Reusable workflow example

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello ${{ inputs.name }}"   # Greet the provided name

